export interface Basket {
  id?: number;
  pricesSum: number;
  user: User;
}

export interface User {
  id?: number;
  firstName: string;
  lastName: string;
  sex: string;
  email: string;
  address: string;
  cin: number;
  birthday: string;
  driverLicence: number;
  phoneNumber: string;
  totalOrder: number;
  isAccountNonExpired: boolean;
  isAccountNonLocked: boolean;
  isCredentialsNonExpired: boolean;
  isEnabled: boolean;
  role: Role;
  username: string;
  authorities: Authority[];
  accountNonExpired: boolean;
  credentialsNonExpired: boolean;
  accountNonLocked: boolean;
  enabled: boolean;
}

export interface Authority {
  authority: string;
}

export interface Role {
  id?: number;
  role: string;
}

export interface BasketArticle {
  id?: number;
  amount: number;
  basket: Basket;
  article: Article;
}

export interface Article {
  id?: number;
  code: number;
  name: null;
  stock: number;
  description: string;
  color: string;
  weight: number;
  price: number;
  url: null;
  subCategory: SubCategory;
  user: User;
  tva: number;
}

export interface SubCategory {
  id?: number;
  name: string;
  category: Category;
}

export interface Category {
  id?: number;
  name: string;
}
// Generated by https://quicktype.io

export interface CreateBasket {
  orderItems: OrderItem[];
}

export interface OrderItem {
  amount: number;
  article: Article;
}
export interface BasketArticleUpdate {
  amount: number;
  basketArticleId: number;
}
export interface subcategoryOfCategory {
  subcategories: SubCategory[];
}
