import { Article } from './article.model';
import { User } from './user';
// Generated by https://quicktype.io

export interface Order {
  id?: number;
  price: number;
  modeOfPayment: string;
  state: string;
  user: User;
} // Generated by https://quicktype.io

export interface orderDetails {
  id?: number;
  amount: number;
  order: Order;
  article: Article;
}
