import { User } from './user';
// Generated by https://quicktype.io

export interface Order {
  id?: number;
  price: number;
  modeOfPayment: string;
  state: string;
  user: User;
} // Generated by https://quicktype.io

export interface orderDetails {
  id?: number;
  amount: number;
  order: Order;
  article: Article;
}
export interface CreateOrder {
  orderItems: OrderItem[];
  modeOfPayment: String;
}

export interface OrderItem {
  amount: number;
  article: Article;
}
export interface Article {
  id?: number;
  code: number;
  name: null;
  stock: number;
  description: string;
  color: string;
  weight: number;
  price: number;
  url: null;
  subCategory: SubCategory;
  user: User;
  tva: number;
}
export interface SubCategory {
  id?: number;
  name: string;
  category: Category;
}

export interface Category {
  id?: number;
  name: string;
}
